---
- name: store puma fact
  set_fact:
    PUMA_CONFIG_PATH: "{{ lookup('template', '../templates/puma_config_path.j2') | trim }}"
    APP_URL: "{{ lookup('template', '../templates/app_url.j2') | trim }}"

- name: config script
  template:
    src: puma.rb.j2
    dest: "{{ PUMA_CONFIG_PATH }}"
  sudo: yes
  sudo_user: "{{ puma_user | default(rvm_user, true) | default(app_user, true) }}"

- name: upstart script
  template:
    src: upstart.conf.j2
    dest: "{{ lookup('template', '../templates/upstart_conf_path.j2') | trim }}"
  sudo: yes
  sudo_user: "{{ rvm_user | default(app_user, true) | default('root', true) }}"
