---
- name: fact
  set_fact:
    APP_URL: "{{ puma_app_url }}"
  tags:
  - facts

- name: config puma.rb
  template:
    dest: "{{ puma_config_file }}"
    src: puma.rb.j2
  sudo: yes
  sudo_user: "{{ puma_user }}"

- name: upstart script
  template:
    dest: "{{ puma_upstart_conf }}"
    src: upstart.conf.j2
  sudo: yes
  sudo_user: "{{ puma_user }}"
