- name: Red Hat | Install EPEL repo
  yum:
    name: "{{ rbenv_epel_repo }}"
    update_cache: yes

- name: Red Hat | Install dependencies
  yum:
    pkg: "{{ item }}"
    update_cache: yes
  with_items: "{{ rbenv_package_names }}"
