#
# Perform the db:migrate rake task
#
- name: Migrate database
  command: "{{ profile }}'bundle exec rake db:migrate'"
  args:
    chdir: "{{ RELEASE_PATH }}"
  run_once: true
  register: result
  changed_when: "'migrating' in result.stdout"
  notify:
  - restart required
