---
- name: Repo
  apt_repository:
    repo: '{{ nginx_apt_repo }}'

- name: Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: nginx_package_names
