---
- name: Site configuration
  template:
    src: site.conf.j2
    dest: "{{ NGINX_SITES_AVAILABLE_PATH }}/{{ site_name }}"
  notify:
  - restart nginx

- name: Enable the site
  file:
    path: "{{ NGINX_SITES_ENABLED_PATH }}/{{ site_name }}"
    src: "{{ NGINX_SITES_AVAILABLE_PATH }}/{{ site_name }}"
    state: link
  notify:
  - restart nginx
