---
- name: store facts
  set_fact:
    APP_URL: "{{ webrick_app_url }}"
  tags:
  - facts

- name: upstart script
  template:
    dest: "{{ webrick_upstart_conf }}"
    src: upstart.conf.j2
  sudo: yes
  sudo_user: "{{ webrick_user }}"
