---
- name: store facts
  set_fact:
    APP_URL: "{{ webrick_app_url }}"
  tags:
  - facts

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
- include: Debian.yml
  when: ansible_os_family == "Debian"
