---
- name: store facts
  set_fact:
    APP_URL: "{{ ansible_default_ipv4.address }}:{{ webrick_port }}"

- name: upstart script
  template:
    src: upstart.conf.j2
    dest: "{{ lookup('template', '../templates/upstart_conf_path.j2') | trim }}"
  sudo: yes
  sudo_user: "{{ rvm_user | default(app_user, true) | default('root', true) }}"
