#
# Define a release id, extract it from git and construct shared and custom folders
#
---
- include: facts.yml
- include: git.yml

- name: Clean shared folders
  file:
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: absent
    force: yes
  when: rails_create_release_result.changed
  with_flattened:
  - rails_deploy_shared_folders
  - rails_deploy_custom_shared_folders

- name: Create custom folders
  file:
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: directory
  with_flattened:
  - rails_deploy_custom_create_folders

- include: shared_folders.yml
