---
- name: Create shared folders
  file:
    path: "{{ RAILS_APP_SHARED_PATH }}/{{ item }}"
    state: directory
  with_flattened:
  - rails_deploy_shared_folders
  - rails_deploy_custom_shared_folders

- name: Link shared folders
  file:
    src: "{{ RAILS_APP_SHARED_PATH }}/{{ item }}"
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: link
    force: yes
  with_flattened:
  - rails_deploy_shared_folders
  - rails_deploy_custom_shared_folders
