---
- name: mods | conf
  file:
    dest: "{{ apache_server_mods_available_folder }}/{{ item.name }}.conf"
    content: "{{ item.conf }}"
  when: (item is mapping)
    and (item.conf is defined)
    and (item.name is defined)
  with_items: apache_server_mods
  notify: restart

- name: mods | load
  file:
    dest: "{{ apache_server_mods_available_folder }}/{{ item.name }}.load"
    content: "{{ item.conf }}"
  when: (item is mapping)
    and (item.load is defined)
    and (item.name is defined)
  with_items: apache_server_mods
  notify: restart

- name: mods | enable
  apache2_module:
    name: "{{ item if item is string else item.name }}"
    state: present
  with_flattened:
  - apache_server_mods
  - "{{ ['ssl'] if apache_server_ssl else [] }}"
  notify: restart

- name: mods | disable
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: apache_server_disable_mods
  notify: restart
