---
- meta: flush_handlers

- name: Check for Restart
  stat:
    path: "{{ RAILS_APP_RESTART_PATH }}"
  register: rails_puma_restart

- when: "{{ rails_puma_restart.stat.exists | bool }}"
  block:
    - name: Debian | Remove RAILS_APP_RESTART_PATH
      file:
        path: "{{ RAILS_APP_RESTART_PATH }}"
        state: absent

    - name: Debian | Upstart | Restart
      shell: "{{ profile }}'restart puma || start puma'"
      when: "{{ puma_service_type == 'upstart' }}"

    - name: Debian | Systemd | Restart
      shell: "{{ profile }}'systemctl --user restart {{ puma_service_name }}.service'"
      when: "{{ puma_service_type == 'systemd' }}"
