---
- meta: flush_handlers

- name: Check for Restart
  stat:
    path: "{{ RAILS_APP_RESTART_PATH }}"
  register: rails_puma_restart

- name: Debian | Remove RAILS_APP_RESTART_PATH
  file:
    path: "{{ RAILS_APP_RESTART_PATH }}"
    state: absent
  when: "{{ rails_puma_restart.stat.exists | bool }}"

- name: Restart
  shell: "{{ profile }}'restart puma || start puma'"
  when: "{{ rails_puma_restart.stat.exists | bool }}"
