#
# Perform the asset:precompile rake task
#
---
- name: Precompile assets
  command: "{{ profile }}'bundle exec rake assets:precompile'"
  args:
    chdir: "{{ RELEASE_PATH }}"
  register: result
  changed_when: "'Writing' in result.stdout"
