#
# perform a bundle run
#
---
- name: Bundle install
  command: >
    {{ profile }}
    'bundle install
    --binstubs {{ bundle_binstubs }}
    --gemfile {{ bundle_gemfile }}
    --path {{ bundle_path }}
    --without {{ bundle_without | join(' ') }}
    {{ bundle_flags | join(' ') }}'
  args:
    chdir: "{{ RAILS_APP_RELEASE_PATH }}"
  register: rails_bundle_result
  changed_when: "'Installing' in rails_bundle_result.stdout"
  notify:
  - restart rails app
