#
# Update the current release link
#
---
- name: Link current
  file:
    path: "{{ rails_current_path }}"
    src: "{{ rails_release_path }}"
    state: link
    force: yes
  notify:
  - restart required
