#
# Update the current release link
#
---
- name: Link current
  file:
    src: "{{ RAILS_APP_RELEASE_PATH }}"
    path: "{{ RAILS_APP_CURRENT_PATH }}"
    state: link
    force: yes
  notify:
  - restart rails app
